FROM node:latest

ENV TZ=Europe/Helsinki
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .

RUN npm install
EXPOSE 8008

CMD ["npm", "run", "start"]